version: "3.9"

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9411/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
      - healthcare-net

  config-server-instance-one:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server-container
    ports:
      - "8888:8888"
    networks:
      - healthcare-net
    depends_on:
      localstack:
        condition: service_healthy  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      retries: 12
      timeout: 3s
      start_period: 120s

  discovery-service-instance-one:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service-container
    ports:
      - "8761:8761"
    networks:
      - healthcare-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      retries: 12
      timeout: 3s
      start_period: 120s

  # api-gateway-instance-one:
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   container_name: api-gateway-container
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   environment:  
  #     - CONFIG_SERVER_URL=http://config-server-instance-one:8888
  #   depends_on:
  #     config-server-instance-one:
  #       condition: service_healthy
  #     discovery-service-instance-one:
  #       condition: service_healthy
  #     zipkin:
  #       condition: service_healthy  
  #   networks:
  #     - healthcare-net

  # member-service-instance-one:
  #   build:
  #     context: ./member-service
  #     dockerfile: Dockerfile
  #   container_name: member-service-container
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #     - "9090:9090"
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-server-instance-one:8888
  #   depends_on:
  #     config-server-instance-one:
  #       condition: service_healthy
  #     discovery-service-instance-one:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #     zipkin:
  #       condition: service_healthy    
  #   networks:
  #     - healthcare-net

  security-service:
    build:
      context: ./security-service
      dockerfile: Dockerfile
    container_name: security-service-container
    restart: always
    ports:
      - "8099:8099"
    environment:
      - CONFIG_SERVER_URL=http://config-server-instance-one:8888
    depends_on:
      config-server-instance-one:
        condition: service_healthy
      discovery-service-instance-one:
        condition: service_healthy
      postgres:
        condition: service_healthy
      # En caso de que lance error, primero hay que iniciar la DB en Postgres (members)
      zipkin:
        condition: service_healthy  
      localstack:
        condition: service_healthy   
    networks:
      - healthcare-net    

  # claim-service-instance-one:
  #   build:
  #     context: ./claim-service
  #     dockerfile: Dockerfile
  #   container_name: claim-service-container
  #   restart: always
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-server-instance-one:8888
  #   depends_on:
  #     config-server-instance-one:
  #       condition: service_healthy
  #     discovery-service-instance-one:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     zipkin:
  #       condition: service_healthy    
  #   networks:
  #     - healthcare-net

  # notification-service-instance-one:
  #   build:
  #     context: ./notification-service
  #     dockerfile: Dockerfile
  #   container_name: notification-service-container
  #   restart: always
  #   ports:
  #     - "8138:8138"
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-server-instance-one:8888
  #   depends_on:
  #     zipkin:
  #       condition: service_healthy  
  #     config-server-instance-one:
  #       condition: service_healthy
  #     discovery-service-instance-one:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy  
  #     kafka:
  #       condition: service_healthy
  #   networks:
  #     - healthcare-net

  # document-service-instance-one:
  #   build:
  #     context: ./document-service
  #     dockerfile: Dockerfile
  #   container_name: document-service-container
  #   restart: always
  #   ports:
  #     - "8085:8085"
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-server-instance-one:8888
  #   depends_on:
  #     zipkin:
  #       condition: service_healthy  
  #     config-server-instance-one:
  #       condition: service_healthy
  #     discovery-service-instance-one:
  #       condition: service_healthy  
  #     localstack:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - healthcare-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - healthcare-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 12
      timeout: 3s

  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   environment:
  #     MYSQL_DATABASE: claims
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - healthcare-net
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 5s
  #     retries: 12
  #     timeout: 3s

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - healthcare-net

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #     - "29092:29092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - healthcare-net
  #   healthcheck:
  #     test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
  #     interval: 5s
  #     timeout: 10s
  #     retries: 12

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,secretsmanager
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack_data:/var/lib/localstack
      - ./scripts:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthcare-net

networks:
  healthcare-net:
    driver: bridge

volumes:
  postgres-data:
  mysql-data:
