spring:
  application:
    name: audit-service

  profiles:
    active: prod

  config:
    import:
      - "optional:configserver:${CONFIG_SERVER_URL}" 
    fail-fast: true

  retry:
    initial-interval: 3000
    max-attempts: 10
    multiplier: 1.5
