spring:
  application:
    name: security-service

  profiles:
    active: prod

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      secretsmanager:
        endpoint: http://localstack:4566

  config:
    import:
      - "aws-secretsmanager:security-service/db"
      - "aws-secretsmanager:security-service/jwt"
      - "optional:configserver:${CONFIG_SERVER_URL}" 
    fail-fast: true

  retry:
    initial-interval: 3000
    max-attempts: 10
    multiplier: 1.5
