spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  kafka:
    bootstrap-servers: kafka:29092 
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
  
management:
  tracing:
    sampling:
      probability: 1.0  # 1.0 = 100% de las trazas (ajustar en producci√≥n)
    propagation:
      type: w3c  # Formato W3C TraceContext
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # URL de tu servidor Zipkin
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  bootstrap-servers: kafka:29092
  member:
    topic: member-topic
  claim:
    topic: claim-topic  
    consumer:
      group-id: notification-group

eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service-instance-one:8761/eureka
    register-with-eureka: true
    fetch-registry: true